### ISSUE TITLE
Forge 47.2.0

### ISSUE THREAD

**Issue by Notlucky101** [Lothrazar/RootsClassic#102]
Minecraft 1.20.1 : Root Classic Ver 131

Single Player

Does not work with current version of Forge

**Comment by PonyWarrior** [comment]
I second this, I can't add this mod to ATM9 for this reason. Please update the forge version.

**Comment by SheReyy** [comment]
+1 would be nice to have the mod updated

**Comment by CaptainPepperjack** [comment]
+1

**Comment by etherealgears** [comment]
+1
