### ISSUE TITLE
Need assistance to update a give command for crystal staff with acceleration spell

### ISSUE THREAD

**Issue by PonyWarrior** [Lothrazar/RootsClassic#112]
Hello, Roots Classic was just added to ATM10 and I was excited to get the acceleration staff once again, however the crystal staff imbuing ritual is still broken, as has been reported many times. In ATM9 I had been able to use a give command to bypass this issue, giving me a staff with the acceleration spell. However in minecraft 1.20.5 the syntax for item NBT was overhauled and I have not managed to replicate the command in the new syntax. Here is the command :

`/give @s rootsclassic:crystal_staff{"rootsclassic:selected":1,"rootsclassic:potency1":3,"rootsclassic:efficiency1":0,"rootsclassic:size1":0,"rootsclassic:effect1":"rootsclassic:oxeye_daisy"}`

Here is my attempt at updating the syntax :

`/give @s rootsclassic:crystal_staff[rootsclassic:selected=1,rootsclassic:potency1=3,rootsclassic:efficiency1=0,rootsclassic:size1=0,rootsclassic:effect1="rootsclassic:oxeye_daisy"]`

Unfortunately it does not work and so far I was unable to figure out why. Any assistance would be appreciated!

**Comment by Mrbysco** [comment]
I'm trying to get more info about the crystal staff imbuing being broken, since I myself have never used the altar setup

**Comment by PonyWarrior** [comment]
> I'm trying to get more info about the crystal staff imbuing being broken, since I myself have never used the altar setup

Well the problem is that the imbuing ritual simply does not work. You can make the staff, you can make the spell powder, but you can't imbue it onto the staff via ritual.

**Comment by Mrbysco** [comment]
What is it supposed to look like? The only thing I've ever done was add spell powder with a stick to create a regular staff.

**Comment by PonyWarrior** [comment]
Here is a clip I've made of the bug. Doesn't matter how you setup the braziers, the ritual does not work.

https://www.youtube.com/watch?v=PYx1E5xHSRY

**Comment by Mrbysco** [comment]
I'll look into it
Also the reason the format changed is because NBT was changed to components. If you craft a staff you should be able to steal it's `rootsclassic:spell` component and put it's contents inside the `roots:spells` component (which is a list of spells instead of using spell1, spell2 etc) required for the crystal staff

**Comment by Mrbysco** [comment]
There's a new version available on CurseForge that should fix the crystal staff spell powder recipe

**Comment by PonyWarrior** [comment]
Just tested and it works! Thank you!
