### ISSUE TITLE
Fruit Salad and Rooty Stew have high saturation values that they shouldn't have

### ISSUE THREAD

**Issue by SihenZhang** [Lothrazar/RootsClassic#14]
Fruit Salad has **112** saturation value and Rooty Stew has **35** saturation value. I think that's a mistake.

![](https://i.imgur.com/X694lUJ.png)
![](https://i.imgur.com/duiUCKw.png)

https://github.com/PrinceOfAmber/RootsClassic/blob/151947ec2a4c8b4e59dbc3f4924510e6f30eb621/src/main/java/elucent/rootsclassic/RegistryManager.java#L236-L237

Saturation Value == healAmount * saturationModifier

healAmout is "Food Points", saturationModifier is "Saturation ratio". (https://minecraft.gamepedia.com/Food)

From this code, the saturationModifier of Rooty Stew is **5.0F**, so the Saturation Value is 7×5.0=35. Also the Saturation Value of Fruit Salsa is 8×14.0=112. 

I don't know this is a bug or ... a feature? Actually, I think these food are so cheap that they shouldn't have such high saturation values.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/roots-classic/files/2659875
