### ISSUE TITLE
Braziers don't keep burning between rituals and performance drops

### ISSUE THREAD

**Issue by kuroyure** [Lothrazar/RootsClassic#18]
The incense braziers wont keep burning when ligthed up between rituals, and don't need to be ligthen up b4 the ritual, also massive performance drops on using the defender armor

**Comment by Lothrazar** [comment]
For performance drops can you add more detail , i dont see it.


FOr braziers. they now have been updated in new versions. they auto light, when you start a ritual and dont, need a flint and steel.   but you still can light by hand if you want.   They wont keep burning for ever yeah that makes sense doesnt it?

**Comment by kuroyure** [comment]
No, i mean they dont keep burning between rituals

**Comment by Lothrazar** [comment]
Working as intended. Cleanin up the 1.12 in case a port to newer versions happens
