### ISSUE TITLE
Living Shovel doesn't repair

### ISSUE THREAD

**Issue by Meatshackles** [Lothrazar/RootsClassic#21]
Minecraft version & Mod Version:
1.12.2 RootsClassic-1.12.2-1.1.2.jar

Single player or Server:
single player

Describe problem (what you were doing / what happened):
Living shovel doesn't repair, missing the line of code on all the other living tools to make it repair randomly

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/roots-classic/files/2660800
