### ISSUE TITLE
Growing Standing Stone doesn't appear to help with the growth of crops at all

### ISSUE THREAD

**Issue by Meatshackles** [Lothrazar/RootsClassic#23]
Minecraft version & Mod Version:
1.12.2 RootsClassic-1.12.2-1.1.2.jar

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Growing Standing Stone doesn't appear to help with the growth of crops at all, compared multiple 3x3 patches of wheat seeds, 1 without the stone, 1 with a stone, and 1 with surrounded with stones and none of them appears to be growing any faster and the 1 without the stone

Crash log (if any):
n/a

**Comment by Spydrouge** [comment]
As part of a larger modpack (Magiculture 2) I made the Roots Classic Growth Staff, and it failed to grow any crops at all on any of it's 16 charges. Tested on all vanilla plants and Pam's Harvestcraft stuff. I don't know if this is useful information for resolving the Growing Standing Stones issue, but I thought I'd mention it in case it helps the mod maintainer.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/roots-classic/files/2660800
