### ISSUE TITLE
Mortar not working

### ISSUE THREAD

**Issue by Meatshackles** [Lothrazar/RootsClassic#25]
Minecraft version & Mod Version:
RootsClassic-1.12.2-1.1.3.jar

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Mortar recipes not working, states invalid recipe, notice sometimes items in mortar move twice when putting them in or they move when right clicking with pestle, I think fake/nonexistant itmes are being added and causing it to be a invalid recipe

Pretty sure its the same issue reported in "Mortar takes ghost items #5"
attached is a screenshot below of me trying to make the acceleration spell component
![2019-01-16_20 20 35](https://user-images.githubusercontent.com/43080251/51288965-51ecb180-19cc-11e9-8dbf-e99ef6c2b8d8.png)

Crash log (if any):
n/a

**Comment by Lothrazar** [comment]
Which recipe and which order did you put them in? Ill check it out

**Comment by Lothrazar** [comment]
Got that sorted out https://minecraft.curseforge.com/projects/roots-classic/files/2665453
