### ISSUE TITLE
Text of Runic Tablet is not displayed correctly in some language.

### ISSUE THREAD

**Issue by 2z6c** [Lothrazar/RootsClassic#30]
On the Runic Tablet, lines are broken automatically at a space between word and word.
But then, in some language (such as Japanese, Chinese, etc.), spaces are not used as a word-delimiter. This causes that the text of the Runic Tablet is displayed within a single line and is often hidden at the edge of the screen.
While it is possible to insert spaces into the text, looks unnatural and makes localization hard.
I hope it to be fixed for localization. Thanks.
![2019-02-19_21 39 59](https://user-images.githubusercontent.com/15604618/53017323-0e85d700-3493-11e9-9769-7a4a9e17dfd3.png)

**Comment by Lothrazar** [comment]
im not sure how you got this translation to work, nobody has ever submitted another language . only english is here 

https://github.com/Lothrazar/RootsClassic/tree/trunk/1.12/src/main/resources/assets/rootsclassic/lang

Someone would have to translate this en_US file to the target language (possible zh_CW for cantonese for example) and make a pull request into it

If they do id love to merge it for any language.  But whatever text you have on screen is not from the mod, idk how that exists <3
