### ISSUE TITLE
Solar Smite Crystal Staff crash

### ISSUE THREAD

**Issue by paraParasect** [Lothrazar/RootsClassic#31]
Minecraft version & Mod Version: 1.12.2, roots classic 1.1.5

Single player or Server: Server

Describe problem (what you were doing / what happened): Using a crystal staff with solar smite to fight undead enemies. Pvp is off in server, spell hit friend, hurt friend, and I crashed to the title screen.

Crash log (if any): N/A

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
"Crash log (if any): N/A"

Theres no crash log. so i guess it didnt crash after all.

Anyway i took a wild guess and maybe its fixed i guess idk . 1.1.6 out soon, even though this issue is 2 years old <3
