### ISSUE TITLE
Some recipes not showing in runic tablet

### ISSUE THREAD

**Issue by Dvoric** [Lothrazar/RootsClassic#34]
Minecraft version & Mod Version:

12.2 &  RootsClassic-1.12.2-1.1.5

Single player or Server:

SINGLE

Describe problem:

Some recipes not showing in runic tablet ... such as Bark Knife or The Mortar

**Comment by Lothrazar** [comment]
Yeah, this is by design. Those are vanilla recipes made in the crafting table, not special runic recipes like Bane of the Undead for example.  JEI shows these just fine
