### ISSUE TITLE
No mana bar in latest update

### ISSUE THREAD

**Issue by PPAChao** [Lothrazar/RootsClassic#37]
Minecraft version & Mod Version:
Minecraft version 1.12.2; mod version 1.1.6

Single player or Server:
Both.

Describe problem (what you were doing / what happened):
After imbuing a wand with spell powder, no mana bar appears, and spells cannot be cast. Holding the right mouse button plays the charging/spellcasting animation, but releasing it does nothing.
This behaviour is consistent across different versions of Forge and whether or not other mods are installed.

Switching back to the previous version fixes this immediately: the mana bar appears and the wand/spell works straight away.

**Comment by Lothrazar** [comment]
Thanks for reporting this on github. discord chat moves really fast. i found a fix , and now im testing a bunch of other stuff to make sure

![cbmana](https://user-images.githubusercontent.com/621529/110157572-30fa9c80-7d9d-11eb-9cf4-f6634f5de1ab.png)
