### ISSUE TITLE
X-Ray altar

### ISSUE THREAD

**Issue by KentaTheButcher** [Lothrazar/RootsClassic#38]
Minecraft version & Mod Version:
1.16.5, the las backport

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The bottom block of the altar sees transparent and allows X-ratín

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment]
Got any screenshots?

**Comment by Mrbysco** [comment]
Nevermind, managed to reproduced it

**Comment by KentaTheButcher** [comment]
> Nevermind, managed to reproduced it

Hey! I've just looked to the curse page and found that you fixed literally the two issues that I reported. I'm so happy with your response and feedback. Hope to see more content in the future:)
