### ISSUE TITLE
Infinite items

### ISSUE THREAD

**Issue by KentaTheButcher** [Lothrazar/RootsClassic#41]
Minecraft version & Mod Version:
1.16.5

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When you put the three items in an altar and right-click it, the last item that you putted will be dropped infinitely and the items from the altar itself won't disappears. 

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment]
Has been reproduced and will be fixed next release
