### ISSUE TITLE
Complete altar setup 

### ISSUE THREAD

**Issue by KentaTheButcher** [Lothrazar/RootsClassic#42]
Minecraft version & Mod Version:
1.16.5

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I'm not sure if it's a bug, but it should be. The thing it's that to do even the most basic rituals, like for the living tools, I had to do an entire altar setup, with every standing stone: mundane and attuned ones. Before that, it says "stones are not placed correctly".

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment]
Found out that the Tablet was displaying the requirements wrong, will be fixed next release
