### ISSUE TITLE
Armor models look wrong

### ISSUE THREAD

**Issue by Mindoth** [Lothrazar/RootsClassic#51]
Minecraft version & Mod Version:
Minecraft version: 1.16.5 & Mod Version: 1.1.11

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
The 3D models of sylvan armor are oversized. Additionally the defender mask renders parts of the sylvan hood when equipped.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment]
What do you mean with "Oversized"? Could you provide an example?
Also what is the Defender Mask you speak of?

**Comment by Mindoth** [comment]
![2021-10-19_23 32 21](https://user-images.githubusercontent.com/18644641/137986316-4d542001-f79d-4595-9e81-798c4a676a62.png)
The sylvan armor is oversized. (Unless of course if that is intentional)

What I meant by the defender mask is the wildwood mask. After equipping it and then equipping the sylvan hood again makes the sylvan hood look like this
![2021-10-19_23 35 40](https://user-images.githubusercontent.com/18644641/137986593-c086be7f-7613-491d-9238-4e734fd671fa.png)
.

**Comment by Mrbysco** [comment]
As far as I was aware the armor looks the same as in the 1.12 branch 🤔 
For the second issue.. I've fixed that in dev :)

**Comment by Mindoth** [comment]
This is how the 1.12.2 version of sylvian armor looks like:
![2021-10-20_00 34 00](https://user-images.githubusercontent.com/18644641/137994003-15227435-6556-419f-a52c-e7735f3c3698.png)

**Comment by Mrbysco** [comment]
![image](https://user-images.githubusercontent.com/9308260/138003186-44d18ffc-2ef7-4334-b2e3-684e685d003b.png)
Apparently I applied scaling twice :) Thanks for letting me know
