### ISSUE TITLE
Casting altar does not consume items

### ISSUE THREAD

**Issue by Mindoth** [Lothrazar/RootsClassic#55]
Minecraft version & Mod Version:
Minecraft version: 1.16.5 & Mod Version: 1.1.12

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Using the casting altar to perform a ritual does not consume given items. (The braziers do consume bark, not the items placed on the altar itself.)

Crash log (if any):

**Comment by Mrbysco** [comment]
Fixed in https://github.com/Lothrazar/RootsClassic/commit/86a73e56349f5d99182c18b8e666c91665e09fc6
