### ISSUE TITLE
Using Tick Acceleration Spell

### ISSUE THREAD

**Issue by Traverse-Joe** [Lothrazar/RootsClassic#58]
Minecraft version & Mod Version:
1.16.5 & 1.1.13

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Using the Acceleration Spell on a machine causes server to crash. Note this is with the crystal wand (Reusable Wand) 

Crash log (if any):
https://pastebin.com/PMA2DNaf

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by TheDyreBanana** [comment]
This is also happening on 1.18 servers as well.

**Comment by Mrbysco** [comment]
I somehow didn't see this issue a month ago when I was fixing other issues, the issue should be fixed in the latest released version
