### ISSUE TITLE
Acceleration wand used on entities hard crashes

### ISSUE THREAD

**Issue by TheDyreBanana** [Lothrazar/RootsClassic#61]
Minecraft version & Mod Version:
Minecraft 1.18
Rootsclassic 1.1.15

Single player or Server:
Both

Describe problem (what you were doing / what happened):
I used the acceleration spell wand on an entity (a cow). It hard crashes client and desktop the second the entity is loaded. 

Crash log (if any):

[crash-2021-12-10_13.14.22-client.txt](https://github.com/Lothrazar/RootsClassic/files/7694741/crash-2021-12-10_13.14.22-client.txt)

**Comment by Mrbysco** [comment]
Will be fixed shortly

**Comment by TheDyreBanana** [comment]
Thank you, will the fix make it so the entity stops crashing the server or will I just have to delete the entity/start over?

**Comment by Mrbysco** [comment]
It'll stop it from crashing

**Comment by Mrbysco** [comment]
New version has been uploaded for 1.16.5, 1.17.1 and 1.18. It'll be up shortly.
