### ISSUE TITLE
Sudden freeze when wearing roots' armor

### ISSUE THREAD

**Issue by touhouzun** [Lothrazar/RootsClassic#64]
Minecraft version & Mod Version:
Minecraft 1.12.2
RootsClassic-1.12.2-1.1.7
I couldn't figure out which mod conflicts with rootsclassic, but rootsclassic have tested with optifine/vanillafix/foamfix/betterhud etc.(two-mods combination), without any lag.

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Recently, when I wear even only one piece of rootsclassic's armors (either sylvan or wildwood), fps drops from 60 to 50 and then freeze to 0 in one minute.

Crash log (if any):
Too laggy that crashing freezes itself !
(Well, please forgive my not-so-good english.)

**Comment by Mrbysco** [comment]
1) 1.12 is lo longer supported unless it's a critical bug
2) Optifine is not supported so reproduce it without

**Comment by touhouzun** [comment]
[latest.log](https://github.com/Lothrazar/RootsClassic/files/7904872/latest.log)
![2022-01-20_19 51 37](https://user-images.githubusercontent.com/31458903/150334325-6020e788-792f-4e2a-9c52-5358d700a678.png)
I couldn't figure it out on my own but it's annoying. Optifine excluded.

**Comment by touhouzun** [comment]
2021/1/21
![捕获2](https://user-images.githubusercontent.com/31458903/150444964-810dfe02-e8b1-4b69-a238-bbde020abf65.PNG)
![2022-01-21_08 37 40](https://user-images.githubusercontent.com/31458903/150444992-07541653-a9c1-4fe3-b2d2-d7eb1a83a52f.png)
![2022-01-21_08 39 52](https://user-images.githubusercontent.com/31458903/150445001-aa9867d7-65dc-4f4e-8c04-954b08d0474b.png)
When wearing sylvan(or wildwood?)armor(especially in second and third person view), my memory usage goes up ridiculously even after removing them.
But they don't cause lag when there are only a few mods.

**Comment by touhouzun** [comment]
[https://github.com/Lothrazar/RootsClassic/blob/trunk/1.12/src/main/java/elucent/rootsclassic/model/ModelDruidRobes.java](url)
[https://github.com/MysticMods/Roots/blob/release/3.1.4/src/main/java/epicsquid/roots/model/armor/ModelSylvanArmor.java](url)
I'm not sure. I know nothing about coding.
Roots 3.1.x 's armor cause no lag at all.

**Comment by touhouzun** [comment]
2021/1/23
[latest.log](https://github.com/Lothrazar/RootsClassic/files/7919556/latest.log)
![2022-01-23_08 55 18](https://user-images.githubusercontent.com/31458903/150660480-4294aa10-949b-47bf-80d8-414d34b2fba1.png)

**Comment by touhouzun** [comment]
![2022-01-24_20 57 36](https://user-images.githubusercontent.com/31458903/150787213-c43d2304-d86d-4cea-8684-9a741b2312f7.png)
![2022-01-24_20 58 14](https://user-images.githubusercontent.com/31458903/150787218-35ed934a-e3e3-4138-9087-90da3e77b5ec.png)
https://github.com/Electroblob77/Wizardry/issues/763

**Comment by touhouzun** [comment]
Emm, I have to set EBwizardry's animation off, or there's no method to solve the problem =(
