### ISSUE TITLE
[1.18.1] Crash when hitting fish with Rose Thorns spell

### ISSUE THREAD

**Issue by Not-February** [Lothrazar/RootsClassic#70]
Minecraft version & Mod Version:

Minecraft 1.18.1, Forge 39.0.59, Roots Classic 1.1.17

Single player or Server

 Single Player

Describe problem (what you were doing / what happened):

Casting a staff imbued with the Rose Thorns component(modifiers or not) at some fish, and the game crashes. It references generic attack damage and I haven't thus far had this happen when casting at land-based passive animals or hostile mobs - only with fish.

Crash log (if any):

https://gist.github.com/Febilian/5bc1cbb91dd401c42020d0a19dffffa4

**Comment by Mrbysco** [comment]
Will be fixed next release
