### ISSUE TITLE
[1.18.1] Only roughly half of the spell component recipes can be modified through data packs

### ISSUE THREAD

**Issue by Not-February** [Lothrazar/RootsClassic#71]
Minecraft version & Mod Version:

Minecraft 1.18.1, Forge 39.0.59, Roots Classic 1.1.17

Single player or Server:

Single Player

Describe problem (what you were doing / what happened):

I noticed this while making recipe changes, but just did some comprehensive testing with every single spell component - some will accept recipe modifications but a majority of them will not. It isn't formatting errors(I've checked all of that) or wrong item/file names to my knowledge, some spells just will not change.

It's interesting to me that some spells *do* work fine with changes and it doesn't seem exclusive to whichever secondary items I'm changing in the recipe itself, which makes me think that they're all *meant* to work with datapack modifications.

I've put together a testing data pack where I changed exactly one ingredient in each recipe(they're all unique from things used in any other recipe chosen somewhat at random, though I don't know if the uniqueness actually matters or not), if you'd like to see for yourself how only some changes apply when the format is ostensibly correct.

[rootsc_test.zip](https://github.com/Lothrazar/RootsClassic/files/7919418/rootsc_test.zip)

I know crafttweaker support exists on 1.18.1 now(it wasn't quite there yet when I first noticed this data related issue), but still thought it might be worth mentioning that the data pack route is only about half functional.

***Quick list of which components can be changed through data packs and which cannot based on my testing:***

Works: 

- Poppy
- White Tulip
- Pink Tulip
- Sunflower
- Rose Bush
- Nether Wart
- Chorus
- Radiant Daisy
- Flare Orchid
- Midnight Bloom

Don't work:

- Blue Orchid
- Allium
- Azure Bluet
- Red Tulip
- Orange Tulip
- Oxeye Daisy
- Dandelion
- Lilac
- Peony
- Apple
- Lily Pad
- Poisonous Potato

**Comment by Mrbysco** [comment]
All work correctly but you weren't overwriting them correctly. The issue is your folder name was incorrect, it's not `recipes/components/COMPONENT_JSON` it's `recipe/component/COMPONENT_JSON`

**Comment by Not-February** [comment]
Weird that some of them still worked then, but okay.

**Comment by Febilian** [comment]
I renamed the folder name and it still doesn't overwrite the specific recipes I mentioned.

**Comment by Mrbysco** [comment]
I believe it has to do with load order and some other weirdness. It's best to use the same folder structure to make sure yours are the ones minecraft uses.

**Comment by Not-February** [comment]
It's odd, I was having issues getting component recipe changes to work even with the correct format until I put the changes into a *separate* data pack and loaded it alongside my other general changes and also removed a change I'd made to the brazier recipe in either data pack. Not 100% sure what was at fault there but it's working now so I won't complain.
