### ISSUE TITLE
[1.16.5] Mortar error

### ISSUE THREAD

**Issue by Ashur420** [Lothrazar/RootsClassic#72]
Minecraft version & Mod Version: 1.16.5

Single player or Server: Single player

Describe problem (what you were doing / what happened):  When using the pestle on the mortar to create a spell receive an overlay message saying, "Recipe found but missing rare materials mixin'".  Nothing else happens.

Crash log (if any):  No error in the log

**Comment by Mrbysco** [comment]
Well... Have you inserted a rare material like an old root?

**Comment by Ashur420** [comment]
Oh... mb, I missed that part in tablet and misunderstood the error.  Yeah that worked.  Thanks for the quick reply!
