### ISSUE TITLE
[1.18.1] Growth Powder issues

### ISSUE THREAD

**Issue by Not-February** [Lothrazar/RootsClassic#73]
Minecraft version & Mod Version:

Minecraft 1.18.1
Roots Classic 1.1.18
Forge 39.0.59

Single player or Server:

Single player

Describe problem (what you were doing / what happened):

1. Growth powder crafts into a stack of 4, but doesn't actually stack naturally. Unsure if intended or not, but I would vastly prefer it at *least* stacking to 8 or 16, because if you shift click your output you're suddenly -4 inventory slots.
2. When used on a dirt block, the powder converts the dirt block into a bit of tall grass instead of an actual grass block. Pretty sure this isn't how it's supposed to work.

**Comment by devjavu7** [comment]
Also the case on 1.16, additionally mutating powder is not stackable and the three flowers make the stone breaking sound when broken.
