### ISSUE TITLE
on startup with modpacktnp limitless 5 - 1.18.2 crash roots classic encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by DoctorEclipse44** [Lothrazar/RootsClassic#75]
Minecraft version & Mod Version: 
1.18.2
1.1.20
Single player or Server: singleplayer

Describe problem (what you were doing / what happened): started up the modpack without changing anything in it and got the error:
 "roots classic encountered an error during the sided_setup event phase java.util.concurrentmodificationexception: null"

Crash log (if any):
https://pastebin.com/TeGRfGhs

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by DoctorEclipse44** [comment]
sorry about bad grammar and stuff, i'm not smart.

**Comment by Mrbysco** [comment]
Have you tried re-installing the modpack?
