### ISSUE TITLE
Healing Poultice

### ISSUE THREAD

**Issue by Lonemind** [Lothrazar/RootsClassic#77]
Minecraft 1.18.2
Roots 1.1.23
Single Player

Healing poultice seems to have no effect after eating.

**Comment by Mrbysco** [comment]
Healing Poultice heals 2,5 hearts upon being eaten

**Comment by Lonemind** [comment]
I'm a github noob so I don't know how but I'd like to reopen this as it's not resolved yet. I think I might know why you believe it is. 

After some further experimentation I've discovered that the healing poultice works fine so long as you eat it when it's stack is higher than 1. If it's the last poultice you have then you eat it without any healing effect.
