### ISSUE TITLE
[1.19.2] Crash trying to boot on a dedicated server

### ISSUE THREAD

**Issue by enigmaquip** [Lothrazar/RootsClassic#80]
Minecraft version & Mod Version:
MC - 1.19.2
Roots - 1.19-1.1.28

Single player or Server:
Server

Describe problem (what you were doing / what happened):

Crash log (if any):
https://mclo.gs/bxki1au

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Mrbysco** [comment]
Your crash log says it's `inventorysorter`

**Comment by enigmaquip** [comment]
Sorry @Mrbysco I posted the wrong one, was checking a bunch of mods
https://mclo.gs/Tq4KefP

**Comment by Mrbysco** [comment]
https://www.curseforge.com/minecraft/mc-mods/roots-classic/files/3945091

**Comment by enigmaquip** [comment]
You are amazing, thanks
