### ISSUE TITLE
Wrong standing stones requirements (1.19)

### ISSUE THREAD

**Issue by bloche1871** [Lothrazar/RootsClassic#82]
It seems that many of the rituals are set to require the wrong standing stone pattern. For example the living tools require a full setup with attuned stones, when they should require no standing stones.

**Comment by Mrbysco** [comment]
It has always required a full setup

**Comment by bloche1871** [comment]
I am basing this on what i could find online on wikis and videos about the mod, and also on the original version of the mod back when it was forked from the original Roots.
You can see the original code for the rituals here, and many of the rituals have different standing stone requirements (unless there is something I misunderstand):
https://github.com/Lothrazar/RootsClassic/blob/60826cb8660dd555713ff6295f4622d263cc2640/src/main/java/elucent/rootsclassic/ritual/RitualManager.java

**Comment by Mrbysco** [comment]
I based the requirements on the 1.12 branch as that was the only version I've ever touched before helping out on the mod

**Comment by Mrbysco** [comment]
So I was unaware that in 1.10 they had different requirements

**Comment by bloche1871** [comment]
OK I see, it looks like the change was introduced with this commit "1.1.2 zenscript for add recipe" which introduced a different format for registering rituals:
https://github.com/Lothrazar/RootsClassic/commit/bf5754b1b513057464cd13a042c3063cf8613cbb

I believe it's safe to assume this is a mistake. It looks like the new ritual registry code was copy-pasted for each ritual, and the author forgot to adjust the "level" requirement. 
In addition, the rituals are laid out logically in the tablet if you go by the original standing stones requirement, but the order no longer makes sense with the new requirements.
