### ISSUE TITLE
Remove Acceleration Spell

### ISSUE THREAD

**Issue by Jona898** [Lothrazar/RootsClassic#91]
I used the crystal Wand with acceleration (full potency) on some machines and it doesn't seem to wear off.
Is there a time how long it lasts?
Is there a way to remove the acceleration? Ether command or in game?

Minecraft version & Mod Version:
1.19.2 - 1.1.34

Single Player

Describe problem (what you were doing / what happened):
Accelerated some Machines and the acceleration does't seem to wear off

**Comment by fkempf78** [comment]
Should be fixed in actual version, but if not using it: just pick up affected machine/block and place it again resets acceleration
