### ISSUE TITLE
Latest forge incompatibility

### ISSUE THREAD

**Issue by Nostalgion** [Lothrazar/RootsClassic#99]
Minecraft version & Mod Version: 1.20.1-1.3.1

Single player or Server: Client

Describe problem (what you were doing / what happened): Incompatible for latest forge version, only up to 40.1.3 iirc, trying to run on 40.1.44

Crash log (if any):  

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by ZestyBlaze** [comment]
Log please?

**Comment by Nostalgion** [comment]
[crash-2023-09-12_01.59.56-fml.txt](https://github.com/Lothrazar/RootsClassic/files/12582873/crash-2023-09-12_01.59.56-fml.txt)
https://mclo.gs/gjtF58g

**Comment by jaeggr** [comment]
Appears to be a max version (for a long while now):
```
[12Oct2023 16:59:18.840] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'rootsclassic', Expected range: '[47,47.1.3]', Actual version: '47.2.0'
```
Is there any way to have this be a min version?

**Comment by toErIpNid** [comment]
This issue is still around. I just got it. 
[latest.log](https://github.com/Lothrazar/RootsClassic/files/12909083/latest.log)

**Comment by drakray** [comment]
This also makes it not compatible with NeoForge (47.1.79)
I'll try manually changing the mods.toml "versionRange" to remove the upper limit, as _sometime_ it work

EDIT: it loaded, so that's a good thing, I'll try to play this way until it crashes XD(hoping it will not)

**Comment by InterPlay02** [comment]
I'm here just to remind that this problem still persists.
`[11:18:54] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'rootsclassic', Expected range: '[47,47.1.3]', Actual version: '47.2.6'
[11:19:01] [main/INFO]: Compatibility level set to JAVA_17`

**Comment by jsaggers** [comment]
Seems this is still a problem and it's the 2nd of January 24 :)
Apparently someone edited the .toml file and fixed it?

**Comment by JoelYoung01** [comment]
Still waiting for this to be resolved!

Coming from attempting to install ATM9

**Comment by FrozenToothpaste** [comment]
Yes its literally just a .toml change. It even loads and works fine. It blows my mind that it hasnt been updated yet?? How else can modpacks include it since Curseforge only accepts Forge mods?

**Comment by FrozenToothpaste** [comment]
If I read the license right, it seems that someone can republish the mod but give full credit to the original author? Correct me if I am wrong about this of course
